name: Push Container to Heroku

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set env vars (prod)
        if: endsWith(github.ref, '/main')
        run: |
          echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME_STAGING }}" >> $GITHUB_ENV
      - name: Set env vars (dev)
        if: endsWith(github.ref, '/dev')
        run: |
          echo "HEROKU_APP_NAME=${{ secrets.HEROKU_APP_NAME_DEV }}" >> $GITHUB_ENV
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Heroku Functions action
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_TESTE_HOME: "Teste Random Data Production"