name: Output metadata
on: workflow_dispatch
jobs: 
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Env
        env:
          TESTE=Teste_ENV
        run: echo "${{ env.TESTE }}"