name: Push Container to Heroku

on:
  push:
    branches:
      - dev
  pull_request_target:
    types: [syncronized]
    branches: 
      - main
      - dev

jobs:
  heroku-deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_STAGING }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
  heroku-deploy-dev:
    if: (github.ref == 'refs/heads/dev') && (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}