name: Push Container to Heroku

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
  push:
    branches:
      - dev

jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch Master
      if: github.ref == 'refs/heads/main'
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_STAGING}}
      run: echo '$HEROKU_APP_NAME'
    - name: Check branch Master
      if: github.ref == 'refs/heads/dev'
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME_DEV}} 
      run: echo '$HEROKU_APP_NAME' 
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ env.HEROKU_APP_NAME }}
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
  send-slack-message:
    needs: [heroku-deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK